### PR TITLE
Theory of heaps translation

### PR DESCRIPTION
**Pull request by OskarSoderberg**
# Theory of Heaps Translation PR Comments
The theory of heaps translation consists in 19 changed/added files. 16 of these are in the src/tricera/postprocessor folder, and the other 3 changes are in the CCReader.scala, ACSLTranslator.scala and Main.scala.

Before merging, it would be great to do the following two fixes:
1. Fix the bug I reported in ADTExploder (my temporary fix can be seen [here](https://github.com/OskarSoderberg/tricera/tree/theory-of-heaps-translation-thesis-version?fbclid=IwAR3F2PY9UDE55PyaYev91pUzNxUo7X0BgueUWgNG5pxqidjU4cfPnL5gJdU))
2. Make it possible to choose an arbitrary starting heap (perhaps there is already an option?).

Below follows a short summary of the changes for each file.

### Main.scala: 
Apply the new processors to the solution.

### ACSLTranslator.scala, CCReader.scala
Add wrapperSort, getterSort, getStructMap to AnnotationContext and make changes accordingly in CCReader.scala.

This was done to be able to easily check whether an IFunction is a wrapper or a getter (see ContractProcessorUtils.scala).

### Postprocessors
Note the following name correspondences between the report and the implementation:
- PostconditionSimplifier -> PostconditionSimplifier
- PrinterPropExtractor -> PointerPropProcessor
- AssignmentExtractor -> AssignmentProcessor
- TOHProcessor -> TheoryOfHeapProcessor
- ADTProcessor -> ADTSimplifier *and* ADTExploder
- ToVarForm -> ToVariableForm
- ACSLProcessor -> ACSLExpressionProcessor
- ClauseRemover -> ClauseRemover

Other than files directly implementing processor steps, the following files were added: 
- ACSLFunctions.scala
- ContractConditionTools.scala
- ContractConditionType.scala
- ContractProcessorUtils.scala
- EqualitySwapper.scala
- HeapRepresentation.scala
- ValSet.scala

#### ACSLFunctions.scala
Defines heap-related ACSL functions and helper functions for creating them.

#### ContractConditionTools.scala
Various tools used for processing contract conditions.

#### ContractConditionType.scala
Definition of the contract condition types (precondition, postcondition and a union of the two).

#### ContractProcessorUtils.scala
Defines classes for easily accessing all information regarding a contract condition and it's terms. Also defines traits for contract processors. 

#### EqualitySwapper.scala
Defines objects and classes for converting expressions to equivalent representations. The ToVariableForm processor is defined here.

#### HeapRepresentation.scala
Defines everything related to a "heap simulator" which can translate TOH expressions to a map containing relevant information.

#### ValSet.scala
Defines objects and classes for treating equivalences. A Val represents a Set[ITerm] where the ITerms are equivalent. A ValSet is a Set[Vals], allowing to add new equivalences. ValSet keeps the number of Vals as low as possible, merging any two Vals whenever they turn out to be equal.

### CODE REVIEW

**Comment by zafer-esen** [comment]
@OskarSoderberg thank you for taking the time to create this PR and the very detailed explanation!

I will go through your additions and might have some questions. 

In the meanwhile, if you have any inputs or unit tests that could be used as regression tests, they would be great to include in this PR.

**Comment by zafer-esen** [comment]
@OskarSoderberg It seems the heap processor is applied even when there is no heap in the program, which leads to an exception. The processors you add should not be applied in those cases. I started a fix in the last commit I pushed to this PR where I do bypass the heap processors if there is no heap, but it looks like there are also changes in ADTExploder -- it accesses ContractProcessorUtils which in turn tries to access the heap.

Since you probably have more insight into this, could you update the PR to not try to access the heap in such cases? ContractProcessorUtils probably does not need to access and store the heap theory in all cases.

Regression tests in `horn-contracts` are currently failing due to this, for instance `contract1.hcc`, since these try to print ACSL annotations but do not use heap.

**Comment by zafer-esen** [comment]
Could you also add high-level descriptions to files/classes/objects you added? Explanatory comments at other locations would also be nice for maintainability.

Also feel free to add preambles to the new files as in existing files with your name.

**Comment by OskarSoderberg** [comment]
> @OskarSoderberg It seems the heap processor is applied even when there is no heap in the program, which leads to an exception. The processors you add should not be applied in those cases. I started a fix in the last commit I pushed to this PR where I do bypass the heap processors if there is no heap, but it looks like there are also changes in ADTExploder -- it accesses ContractProcessorUtils which in turn tries to access the heap.
> 
> Since you probably have more insight into this, could you update the PR to not try to access the heap in such cases? ContractProcessorUtils probably does not need to access and store the heap theory in all cases.
> 
> Regression tests in `horn-contracts` are currently failing due to this, for instance `contract1.hcc`, since these try to print ACSL annotations but do not use heap.

 Nice catch, was purely focused on the heap case during my thesis work. All the code I added in the main file should be skipped if there is no heap, so I [added an if statement wrapping my additions](https://github.com/uuverifiers/tricera/pull/4/commits/7ce1ed26828af016a2d1eae6c1ae9b894043721d). ADTExploder will only access the heap if called as a ContractProcessor.

**Comment by OskarSoderberg** [comment]
Added preambles and high-level descriptions as well:)

**Comment by OskarSoderberg** [comment]
image
FYI, got this error when running `sbt assembly` so had to comment out the `logPredicates` arg to be able to run

**Comment by OskarSoderberg** [comment]
image
Was unable to run all tests, got this error on `preprocess-1.c`. Not really sure how to resolve it.

**Comment by OskarSoderberg** [comment]
Also, I guess this is already clear but still wanted to emphasize that the theory of heaps translation should not make any claims on correctness in it's current state (however using it with Frama-C and Saida is perfectly fine as Frama-C stands for the correctness claims!). As was outlined in the report there are numerous areas of improvement and more thorough testing would likely reveal further information about its limitations and capabilities.

**Comment by zafer-esen** [comment]
> image FYI, got this error when running `sbt assembly` so had to comment out the `logPredicates` arg to be able to run

Looks like sbt is trying to use an older version of Eldarica that is cached on your system. You can use `sbt "clean;update;assembly"` to force update dependencies.

**Comment by zafer-esen** [comment]
> image Was unable to run all tests, got this error on `preprocess-1.c`. Not really sure how to resolve it.

The error message seems to be actually wrong, it confuses the C preprocessor with the TriCera preprocessor... Disregarding that, it looks like TriCera is unable to call `cpp`, does `cpp --version` work when called from the command line? If not and if you want to skip these tests, you can remove [these lines](https://github.com/uuverifiers/tricera/blob/53f5f6d82cf7a4ee042443646041462364d7956f/regression-tests/horn-hcc/runtests#L45-L51) during testing. Alternatively, you can also comment out [this line](https://github.com/uuverifiers/tricera/blob/53f5f6d82cf7a4ee042443646041462364d7956f/regression-tests/runalldirs#L3) to continue on failure, and check the outputs of failing tests. 

Each directory in regression tests continue a file named `Answers`, and running the tests will produce a file named `Output` in each directory, which we check the diff for. If some tests fail but its `Output` looks correct (likely due to changes you made), you can update `Answers` accordingly and push it.

For instance there are print statements that seem to be [failing at least one test](https://github.com/uuverifiers/tricera/actions/runs/6517050190/job/17713602833?pr=4) right now. We could update `Answers`, but I think these look like debugging messages useful for development, so they should not be printed by default. You can tie the printing of such messages to the `-dev` option (`TriCeraParameters.devMode`).

**Comment by zafer-esen** [comment]
> > @OskarSoderberg It seems the heap processor is applied even when there is no heap in the program, which leads to an exception. The processors you add should not be applied in those cases. I started a fix in the last commit I pushed to this PR where I do bypass the heap processors if there is no heap, but it looks like there are also changes in ADTExploder -- it accesses ContractProcessorUtils which in turn tries to access the heap.
> > Since you probably have more insight into this, could you update the PR to not try to access the heap in such cases? ContractProcessorUtils probably does not need to access and store the heap theory in all cases.
> > Regression tests in `horn-contracts` are currently failing due to this, for instance `contract1.hcc`, since these try to print ACSL annotations but do not use heap.
> 
> Nice catch, was purely focused on the heap case during my thesis work. All the code I added in the main file should be skipped if there is no heap, so I [added an if statement wrapping my additions](https://github.com/uuverifiers/tricera/pull/4/commits/7ce1ed26828af016a2d1eae6c1ae9b894043721d). ADTExploder will only access the heap if called as a ContractProcessor.

Could any of the processors you added be applicable when there is no heap?

**Comment by OskarSoderberg** [comment]
> Could any of the processors you added be applicable when there is no heap -- for instance ADTSimplifier should be more general?

Yes ADTSimplifier would be the only one that is applicable when there is no heap. However, the current implementation uses an instance of ContractConditionInfo to easily check whether MonoSortedIFunctions are struct constructors or not. 

I suppose the easiest way to make the ADTSimplifier independent of ContractConditionInfo would be to let ADTTermSimplifier take a structMap as input (the one returned by `acslContext.getStructMap`) and use this for struct constructor checks. Then `apply` would take two arguments `(structMap, expr)` and return `(new ADTTermSimplifier(structMap)).visit(expr)` and processContractCondition would call `apply(cci.acslContext.getStructMap)`.

**Comment by zafer-esen** [comment]
Closing this as it is subsumed by #13.

**Pull request closed without merging**
